// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


/*AUTHENTICATION*/
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const ADD_THIRD_PARTY_SUCCESS = 'ADD_THIRD_PARTY_SUCCESS';
export const ADD_THIRD_PARTY_FAIL = 'ADD_THIRD_PARTY_FAIL';
export const GET_THIRD_PARTIES_SUCCESS = 'GET_THIRD_PARTIES_SUCCESS';
export const GET_THIRD_PARTIES_FAIL = 'GET_THIRD_PARTIES_FAIL';
export const DELETE_THIRD_PARTY_SUCCESS = 'DELETE_THIRD_PARTY_SUCCESS';
export const DELETE_THIRD_PARTY_FAIL = 'DELETE_THIRD_PARTY_FAIL';
export const UPDATE_THIRD_PARTY_SUCCESS = 'UPDATE_THIRD_PARTY_SUCCESS';
export const UPDATE_THIRD_PARTY_FAIL = 'UPDATE_THIRD_PARTY_FAIL';


/*CONFIGURATION*/
export const GET_FAILURES_SUCCESS = 'GET_FAILURES_SUCCESS';
export const GET_FAILURES_FAIL = 'GET_FAILURES_FAIL';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAIL = 'GET_TYPES_FAIL';

export const ADD_FAILURE_SUCCESS = 'ADD_FAILURE_SUCCESS';
export const ADD_FAILURE_FAIL = 'ADD_FAILURE_FAIL';

export const DELETE_FAILURE_SUCCESS = 'DELETE_FAILURE_SUCCESS';
export const DELETE_FAILURE_FAIL = 'DELETE_FAILURE_FAIL';

export const UPDATE_FAILURE_SUCCESS = 'UPDATE_FAILURE_SUCCESS';
export const UPDATE_FAILURE_FAIL = 'UPDATE_FAILURE_FAIL';

export const ADD_TYPE_SUCCESS = 'ADD_TYPE_SUCCESS';
export const ADD_TYPE_FAIL = 'ADD_TYPE_FAIL';

export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS';
export const DELETE_TYPE_FAIL = 'DELETE_TYPE_FAIL';

export const UPDATE_TYPE_SUCCESS = 'UPDATE_TYPE_SUCCESS';
export const UPDATE_TYPE_FAIL = 'UPDATE_TYPE_FAIL';

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';


/*ASSETS*/
export const GET_TREE_ASSETS_SUCCESS = 'GET_TREE_ASSETS_SUCCESS';
export const GET_TREE_ASSETS_FAIL = 'GET_TREE_ASSETS_FAIL';
export const GET_FIXED_ASSETS_SUCCESS = 'GET_FIXED_ASSETS_SUCCESS';
export const GET_FIXED_ASSETS_FAIL = 'GET_FIXED_ASSETS_FAIL';

export const ADD_FIXED_ASSET_SUCCESS = 'ADD_FIXED_ASSET_SUCCESS';
export const ADD_FIXED_ASSET_FAIL = 'ADD_FIXED_ASSET_FAIL';

export const DELETE_FIXED_ASSET_SUCCESS = 'DELETE_FIXED_ASSET_SUCCESS';
export const DELETE_FIXED_ASSET_FAIL = 'DELETE_FIXED_ASSET_FAIL';

export const UPDATE_FIXED_ASSET_SUCCESS = 'UPDATE_FIXED_ASSET_SUCCESS';
export const UPDATE_FIXED_ASSET_FAIL = 'UPDATE_FIXED_ASSET_FAIL';

export const GET_PHYSICAL_ASSETS_SUCCESS = 'GET_PHYSICAL_ASSETS_SUCCESS';
export const GET_PHYSICAL_ASSETS_FAIL = 'GET_PHYSICAL_ASSETS_FAIL';


export const GET_EQUIPMENT_SUCCESS = 'GET_EQUIPMENT_SUCCESS';
export const GET_EQUIPMENT_FAIL = 'GET_EQUIPMENT_FAIL';
export const ADD_PHYSICAL_ASSET_SUCCESS = 'ADD_PHYSICAL_ASSET_SUCCESS';
export const ADD_PHYSICAL_ASSET_FAIL = 'ADD_PHYSICAL_ASSET_FAIL';

export const DELETE_PHYSICAL_ASSET_SUCCESS = 'DELETE_PHYSICAL_ASSET_SUCCESS';
export const DELETE_PHYSICAL_ASSET_FAIL = 'DELETE_PHYSICAL_ASSET_FAIL';

export const UPDATE_PHYSICAL_ASSET_SUCCESS = 'UPDATE_PHYSICAL_ASSET_SUCCESS';
export const UPDATE_PHYSICAL_ASSET_FAIL = 'UPDATE_PHYSICAL_ASSET_FAIL';

export const ADD_FILE_TO_PHYSICAL_ASSET_SUCCESS = 'ADD_FILE_TO_PHYSICAL_ASSET_SUCCESS';
export const ADD_FILE_TO_PHYSICAL_ASSET_FAIL = 'ADD_FILE_TO_PHYSICAL_ASSET_FAIL';

export const GET_TOOLS_SUCCESS = 'GET_TOOLS_SUCCESS';
export const GET_TOOLS_FAIL = 'GET_TOOLS_FAIL';

export const ADD_TOOL_SUCCESS = 'ADD_TOOL_SUCCESS';
export const ADD_TOOL_FAIL = 'ADD_TOOL_FAIL';

export const DELETE_TOOL_SUCCESS = 'DELETE_TOOL_SUCCESS';
export const DELETE_TOOL_FAIL = 'DELETE_TOOL_FAIL';

export const UPDATE_TOOL_SUCCESS = 'UPDATE_TOOL_SUCCESS';
export const UPDATE_TOOL_FAIL = 'UPDATE_TOOL_FAIL';

export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS';
export const GET_FILES_FAIL = 'GET_FILES_FAIL';

export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';
export const ADD_FILE_FAIL = 'ADD_FILE_FAIL';

export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL';


//STORE
export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS';
export const GET_STORE_FAIL = 'GET_STORE_FAIL';
export const SYNC_STORE_SUCCESS = 'SYNC_STORE_SUCCESS';
export const SYNC_STORE_FAIL = 'SYNC_STORE_FAIL';
export const SET_SYNC_STORE_LOADING = 'SET_SYNC_STORE_LOADING';
export const REMOVE_SYNC_STORE_LOADING = 'REMOVE_SYNC_STORE_LOADING';

export const GET_REQUIREMENTS_SUCCESS = 'GET_REQUIREMENTS_SUCCESS';
export const GET_REQUIREMENTS_FAIL = 'GET_REQUIREMENTS_FAIL';

export const ADD_REQUIREMENT_SUCCESS = 'ADD_REQUIREMENT_SUCCESS';
export const ADD_REQUIREMENT_FAIL = 'ADD_REQUIREMENT_FAIL';

export const DELETE_REQUIREMENT_SUCCESS = 'DELETE_REQUIREMENT_SUCCESS';
export const DELETE_REQUIREMENT_FAIL = 'DELETE_REQUIREMENT_FAIL';

export const UPDATE_REQUIREMENT_SUCCESS = 'UPDATE_REQUIREMENT_SUCCESS';
export const UPDATE_REQUIREMENT_FAIL = 'UPDATE_REQUIREMENT_FAIL';


//MANAGEMENT WORK ORDER
export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS';
export const GET_WORKS_FAIL = 'GET_WORKS_FAIL';


export const ADD_WORK_SUCCESS = 'ADD_WORK_SUCCESS';
export const ADD_WORK_FAIL = 'ADD_WORK_FAIL';

export const DELETE_WORK_SUCCESS = 'DELETE_WORK_SUCCESS';
export const DELETE_WORK_FAIL = 'DELETE_WORK_FAIL';

export const UPDATE_WORK_SUCCESS = 'UPDATE_WORK_SUCCESS';
export const UPDATE_WORK_FAIL = 'UPDATE_WORK_FAIL';
export const UPDATE_WORK_SUPERVISOR_SUCCESS = 'UPDATE_WORK_SUPERVISOR_SUCCESS';
export const UPDATE_WORK_SUPERVISOR_FAIL = 'UPDATE_WORK_SUPERVISOR_FAIL';

export const GET_WORK_REQUEST_SUCCESS = 'GET_WORK_REQUEST_SUCCESS';
export const GET_WORK_REQUEST_FAIL = 'GET_WORK_REQUEST_FAIL';

export const ADD_WORK_REQUEST_SUCCESS = 'ADD_WORK_REQUEST_SUCCESS';
export const ADD_WORK_REQUEST_FAIL = 'ADD_WORK_REQUEST_FAIL';

export const GENERATE_OT_SUCCESS = 'GENERATE_OT_SUCCESS';
export const GENERATE_OT_FAIL = 'GENERATE_OT_FAIL';

export const ADD_RESOURCE_OT_SUCCESS = 'ADD_RESOURCE_OT_SUCCESS';
export const ADD_RESOURCE_OT_FAIL = 'ADD_RESOURCE_OT_FAIL';

export const DELETE_RESOURCE_OT_SUCCESS = 'DELETE_RESOURCE_OT_SUCCESS';
export const DELETE_RESOURCE_OT_FAIL = 'DELETE_RESOURCE_OT_FAIL';

export const ADD_HELPER_OT_SUCCESS = 'ADD_HELPER_OT_SUCCESS';
export const ADD_HELPER_OT_FAIL = 'ADD_HELPER_OT_FAIL';

export const DELETE_HELPER_OT_SUCCESS = 'DELETE_HELPER_OT_SUCCESS';
export const DELETE_HELPER_OT_FAIL = 'DELETE_HELPER_OT_FAIL';


//GRAPHICS
export const GET_GRAPHICS_PERSONNEL_SUCCESS = 'GET_GRAPHICS_PERSONNEL_SUCCESS';
export const GET_GRAPHICS_PERSONNEL_FAIL = 'GET_GRAPHICS_PERSONNEL_FAIL';

export const GET_GRAPHICS_OT_SUCCESS = 'GET_GRAPHICS_OT_SUCCESS';
export const GET_GRAPHICS_OT_FAIL = 'GET_GRAPHICS_OT_FAIL';


export const GET_TOTAL_TOTAL_OT_SUCCESS = 'GET_TOTAL_TOTAL_OT_SUCCESS';
export const GET_TOTAL_TOTAL_OT_FAIL = 'GET_TOTAL_TOTAL_OT_FAIL';

export const GET_INDICATORS_SUCCESS = 'GET_INDICATORS_SUCCESS';
export const GET_INDICATORS_FAIL = 'GET_INDICATORS_FAIL';

export const GET_GRAPHICS_COST_DAY_SUCCESS = 'GET_GRAPHICS_COST_DAY_SUCCESS';
export const GET_GRAPHICS_COST_DAY_FAIL = 'GET_GRAPHICS_COST_DAY_FAIL';

export const GET_GRAPHICS_TOTAL_COST_SUCCESS = 'GET_GRAPHICS_TOTAL_COST_SUCCESS';
export const GET_GRAPHICS_TOTAL_COST_FAIL = 'GET_GRAPHICS_TOTAL_COST_FAIL';


export const GET_TOTAL_OT_SUCCESS = 'GET_TOTAL_OT_SUCCESS';
export const GET_TOTAL_OT_FAIL = 'GET_TOTAL_OT_FAIL';